### ISSUE TITLE
Image sequence vs. AV1 Sequences 

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-avif#108]
The image sequence section (https://aomediacodec.github.io/av1-avif/#image-sequences) should be clarified regarding how multiple AV1 sequences (e.g. 2 sets of OBUs each starting with a Sequence Header OBU) should be treated. 
Options are:
1. they are not permitted. One pict track means one AV1 sequence, which means one Sequence Header OBU
2. they are permitted but each sequence should correspond to a single sample description entry: 1 sample description entry matches 1 Sequence Header OBU
3. they are permitted and can be mixed in the scope of one sample description entry as long as it does not violate the matching rules for the content of the av1C box.

**Comment by cconcolato** [comment]
@leo-barnes @wantehchang do you remember what the outcome of this discussion was?

**Comment by leo-barnes** [comment]
Hmmm. No unfortunately not. I have a vague memory of the conclusion being that we wanted things to be simple, but can't remember the exact details on this issue.

I think the discussion was related to this issue:
https://github.com/AOMediaCodec/av1-avif/issues/75#issuecomment-696898914

I can't find anything in the older meeting notes either unfortunately.

**Comment by cconcolato** [comment]
Ok, here is a [script](https://gist.github.com/cconcolato/037b965578b0ff55dd057a45a26eb433) to experiment with multiple image sequences. It uses MP4Box to concatenate 3 sequences of the same stream encoded with 3 different resolutions. The results in Chrome (image sequences don't seem enabled yet in Firefox) are interesting:
- 'spark_scene_forced_cat_decreasing' : the track uses only one sample description entry, corresponding to the first Sequence Header in the stream, corresponding to the highest resolution. When played in Chrome, it starts fine but when the image resolution changes it starts to display a white rectangle until the end of the sequence, then it loops and starts displaying again.
- 'spark_scene_forced_cat_increasing': similar to the previous test but the streams are concatenated in increasing resolution and the sample description documents the lowest resolution. Similar behavior.
- 'spark_scene_raw_cat_decreasing'/'spark_scene_raw_cat_increasing': the track uses 3 sample descriptions and each sample uses the corresponding sample description index. Chrome does not display them at all.

Note that if the same configurations are used in a video track (with handler `vide` instead of `pict`and in a file with `.mp4` extension instead of `.avif`), both Chrome and Firefox play fine.

So either: 
- we need to update the spec to match the current Chrome implementation and restrict the complexity for image sequence players in general. This can be done by saying that a) multiple sample description entries shall not be used and b) that Sequence Header OBUs shall not change throughout the sequence. This may be overly strict. We could let SH change in lower level features but not let the image resolution change.
- we leave the spec as is for parity between video and image sequences and file bugs with implementations
