### ISSUE TITLE
Definition of HLG and PQ gamma curves

### ISSUE THREAD

**Issue by novomesk** [AOMediaCodec/av1-avif#110]
Hello,
AVIF, but also HEIC or JPEG-XL can use enum defined color profiles. There are HLG and PQ transfer functions in those enums.

How are those HLG and PQ TRCs mathematically defined and where?

I wish to share the information with Marti Maria (author of lcms2), so we have compatible implementation everywhere.

**Comment by joedrago** [comment]
Both are defined in BT.2100:

https://www.itu.int/rec/R-REC-BT.2100-2-201807-I/en

**Comment by cconcolato** [comment]
@novomesk can we close this issue?

**Comment by novomesk** [comment]
Thanks!
