### ISSUE TITLE
Please register the Internet Media Type (or types) soon

### ISSUE THREAD

**Issue by svgeesus** [AOMediaCodec/av1-avif#119]
The Internet Media Type (MIME type) for AVIF has not been registered. Developer pages such as [MDN](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#AVIF) are referencing `image/avif` and there is a [MIME type registration appendix](https://aomediacodec.github.io/av1-avif/#mime-registration) but this has not been submitted to IANA. Please do so sooner rather than later; I can help if required.

Two related issues:

1) Is `image/avif` to be used both for still images and also for image sequences? I ask because SC29 has registered separate types for images and image sequences:

* mage/heic 
* image/heic-sequence 
* image/heif
* image/heif-sequence

I can see advantages and disadvantages to registering a pair of types, so I am just asking to be sure that this has been considered, not to advocate a particular approach

2) My understanding is that an AVIF image is a valid type of HEIF, but the [registration of `image/heif'](https://www.iana.org/assignments/media-types/image/heif) seems oddly constrained such that only one specific brand is allowed and thus, AVIF could not use `image/heif` despite being a valid HEIF. Am I reading this right?

> The MIME subtype name may be 'heif' only if the file conforms to 
   the requirements of the 'mif1' brand, and contains that brand as a 
   compatible brand.

**Comment by joedrago** [comment]
I believe from the meetings that they decided on using a single MIME type (`image/avif`) for both images and sequences, and that is how Chrome is implemented due to that. @cconcolato will have to remark on the MIME registration aspect.

**Comment by baumanj** [comment]
> Is `image/avif` to be used both for still images and also for image sequences?

Yes, see the discussion in https://github.com/AOMediaCodec/av1-avif/issues/59

**Comment by svgeesus** [comment]
Thanks, glad to see it was discussed.

My main point is to get the registration done, because implementations are shipping and the MIME type is already being used. In the unlikely event that the final specification requires some different handling or specification links need to be updated, the IANA registration can always be updated.

**Comment by cconcolato** [comment]
Thanks @svgeesus for the reminder. I've been discussing with IANA for quite some time and my understanding is that we need to have a published specification with the MIME type, to refer to it. Since the first version defined 2 MIME types and now we are heading towards only one, the idea was to have the next version of AVIF published first, before continuing the process.

**Comment by wantehchang** [comment]
Cyril: Thank you for the status update. I don't know when the next version of AVIF is expected to be published. If IANA allows a media type registration to be amended, would it make sense to first register the image/avif media type as defined in v1.0.0 of AVIF (i.e., for AVIF Image Item only)? The "partial" registration should help relieve the pressure. And then, when the next version of AVIF is published, we amend the registration to extend the media type to AVIF Image Sequence.

**Comment by cconcolato** [comment]
Done:
https://www.iana.org/assignments/media-types/image/avif

**Comment by wantehchang** [comment]
Thank you very much, Cyril!
