### ISSUE TITLE
Restriction on AV1CodecConfigurationBox not compatible with AV1 ISOBMFF mapping

### ISSUE THREAD

**Issue by aklemets** [AOMediaCodec/av1-avif#13]
In this spec it says that the AV1CodecConfigurationBox shall not contain any Sequence Header OBUs. But in the AV1 ISOBMFF mapping spec, it says the opposite. In that spec, the Sequence Header is mandatory and it shall be the first one.

This discrepancy is problematic because ideally the AV1F spec should just be a superset of the AV1-ISOBMFF mapping spec. It should not define things that directly conflict with the AV1-ISOBMFF mapping spec.
It gets particularly confusing with the AV1F file contains an image sequence. As defined in the HEIF spec, an image sequence is stored in a 'pict' track, which is defined just like a video track, except that the HandlerType is 'pict'. But an AV1 video track would require sequence Sequence Header OBUs in the AV1CodecConfigurationBox. The result is that within the same AV1F file, there will be conflicting requirements for the AV1CodecConfigurationBox depending on whether AV1CodecConfigurationBox is used for a still image vs. a picture track. This is not a good situation, IMO.

**Comment by cconcolato** [comment]
> In this spec it says that the AV1CodecConfigurationBox shall not contain any Sequence Header OBUs. But in the AV1 ISOBMFF mapping spec, it says the opposite.
You're misreading the AV1-ISOBMFF. There the SH OBUs are allowed in the av1C but not mandated. If present they shall be first.

> This discrepancy is problematic because ideally the AV1F spec should just be a superset of the AV1-ISOBMFF mapping spec. It should not define things that directly conflict with the AV1-ISOBMFF mapping spec.

I agree in general. But we have to balance the ability to round-trip to/from an AV1-ISOBMFF file, with potential drawbacks. In that particular case, in a video stream, a redundant header is negligible; for a single image, it might be inefficient to have it both in the sample and in the item config. That said, the current 'SHALL not' is too strict and should probably be 'SHOULD not'. 

> As defined in the HEIF spec, an image sequence is stored in a 'pict' track, which is defined just like a video track, except that the HandlerType is 'pict'. But an AV1 video track would require sequence Sequence Header OBUs in the AV1CodecConfigurationBox. The result is that within the same AV1F file, there will be conflicting requirements for the AV1CodecConfigurationBox depending on whether AV1CodecConfigurationBox is used for a still image vs. a picture track. This is not a good situation, IMO.

Again, I think I understand the concern but it is based on a wrong assumption of the AV1-ISOBMFF spec.
