### ISSUE TITLE
Clarify semantics of ispe

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-avif#132]
In relation to https://github.com/MPEGGroup/FileFormat/issues/26, we should clarify that for AV1, width and height shall match max_frame_width/max_frame_height, and that render_width/render_height are ignored.

**Comment by tdaede** [comment]
Just found this after implementing https://github.com/gpac/gpac/pull/1710, I will submit a follow up PR to switch it to max_frame_width and max_frame_height.

**Comment by cconcolato** [comment]
I'm trying to prepare a PR for this issue but I have some questions.

The current spec says:
> In the absence of a lsel property associated with the item:
> * If an OperatingPointSelectorProperty is associated with an AV1 Image Item, the ispe property associated with this item shall describe the dimension of the output image corresponding to the operating point.
> * If no OperatingPointSelectorProperty is associated with an AV1 Image Item, the ispe documents the dimensions of the operating point whose index is 0.
> NOTE: The dimensions of possible intermediate output images might not match the ones given in the ispe property. Renderers are expected to scale the output image to match the ispe property.

The max frame width and max frame height are coded independently of the operating points (outside the loop), meaning they are the max across all operating points I assume.  How do you determine the "dimension of the output image corresponding to the operating point" ?

**Comment by tdaede** [comment]
> The max frame width and max frame height are coded independently of the operating points (outside the loop), meaning they are the max across all operating points I assume. How do you determine the "dimension of the output image corresponding to the operating point" ?

I don't think you can, at least without looping through all the frames (which is something this change is trying to avoid). I think the "corresponding to the operating point" language would have to be removed. For most usages of operating points (e.g. various levels for HW decoders) I don't see this as an issue - if you choose a lower operating point it's still most useful to know what the max size is. It's a little bit more unclear with the presence of `a1op` - here I could see wanting to use the operating point's resolution, but I also can't think of an application which would benefit from it.

It's worth noting that disregarding operating points for this sort of metadata would be more consistent with the ISOBMFF packaging:
>The width and height fields of the VisualSampleEntry SHALL equal the values of max_frame_width_minus_1 + 1 and max_frame_height_minus_1 + 1 of the Sequence Header OBU applying to the samples associated with this sample entry.

However, the ISOBMFF packaging does not have an equivalent to `a1op`.

**Comment by leo-barnes** [comment]
Given that we have fully specified which layer we expect to be decoded as
- Operating point as given by `a1op` if present, else 0
- Layer given by `lsel` if present, else highest layer in operating point
can we just make the `ispe` map to the frame dimensions of the specific layer?

**Comment by cconcolato** [comment]
We could but that makes it harder for the parsers/packagers. They have to parse the frame header.

**Comment by leo-barnes** [comment]
> We could but that makes it harder for the parsers/packagers. They have to parse the frame header.

Not sure I understand, but I'm not completely clear on how the max_frame_width/height differs from the dimensions of the actual decoded frame, so I may be missing things.

By definition, the `ispe` needs to match the dimensions of whatever you get when you decode a specific item (with the idea being that HEIF parsers should be able to reason about dimensions *without* having to parse any elementary streams). This means it needs to match the dimensions of the specific layer that the decoder outputs. If `lsel` and `a1op` are used, I would assume this means it **shall** match the dimensions of the selected layer.

In the absence of `lsel` and `a1op`, we have wording in place to explain which layer shall be decoded, but allow for the decoder to decode intermediate layers if it wants to do progressive refinement. But I would still expect the `ispe` to match the dimensions of the final layer indicated by the spec.

If this is not the case, we would need to add wording to the spec to say that the decoder should scale the output to the dimensions given by the `ispe` in case they don't match the dimensions of the decoded frame.
