### ISSUE TITLE
Wiki : add libgd support

### ISSUE THREAD

**Issue by Nuranto** [AOMediaCodec/av1-avif#136]
Something to add to https://github.com/AOMediaCodec/av1-avif/wiki

libgd added support for AVIF : 
https://github.com/libgd/libgd/releases

That means php-gd will or already is (I don't know ^^), which is a good news for avif !

See also : https://bugs.php.net/bug.php?id=78832

Another thing that could be added on that wiki is browser support. See https://caniuse.com/?search=avif

**Comment by cconcolato** [comment]
Done. Thank you.
