### ISSUE TITLE
still_picture and reduced_still_picture_header in items

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-avif#14]
As discussed during today's AOM Image call:
- why do we require still_picture flag set to 1 in item data? That requires flipping this bit when creating an image item from a KEY FRAME in a video sequence. What do we gain by having this flag set?
- why are we recommending to have reduced_still_picture_header flag set to 1? Should leave freedom to encoders to do what they want.

**Comment by lambdapioneer** [comment]
- I think the intention was that if the stream is passed to an independent (hardware) AV1 processing module it can early on decide to optimize for still images. In particular it can avoid allocating/initializing buffers used for inter-frame references.
- Probably not a hard decision as encoders would naturally use this to minimize the bitstream. However, I think it's beneficial to reference this in the specification. But maybe it has a better place in a `NOTE` section.

**Comment by cconcolato** [comment]
Discussed at AOMI meeting.

Agreement to say that it is recommended to set still_picture to 1, but not mandatory. It allows using a video sequence key frame as is, without having to flip this bit. Also useful, in dual headed files.

We keep the text about reduced_still_picture_header as a recommendation.
