### ISSUE TITLE
Last layer_size entry in a1lx is redundant

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/av1-avif#140]
The last layer size can simply be inferred to be the entire Item size.

Not only does this shrink layer_size to only 3 entries, but by not coding the largest layer size it makes it much more likely to be coded as a u16, saving up to 10 bytes in the best case.

**Comment by leo-barnes** [comment]
I'll hold off on #131 until we've decided since it's using the `a1lx` box.
