### ISSUE TITLE
Invalid test files: ItemInfoEntry (infe) flags should be 0

### ISSUE THREAD

**Issue by baumanj** [AOMediaCodec/av1-avif#146]
Per ISOBMFF (ISO/IEC 14496-12:2015) § 8.11.6.2, **Item Information Box, Syntax**:

> ```
> aligned(8) class ItemInfoEntry
>       extends FullBox(‘infe’, version, 0)
> ```

per § 4.2:

> Many objects also contain a version number and flags field:
> ```
> aligned(8) class FullBox(unsigned int(32) boxtype, unsigned int(8) v, bit(24) f)
>    extends Box(boxtype) {
>    unsigned int(8)   version = v;
>    bit(24)           flags = f;
> }
> ```
> The semantics of these two fields are:
> version is an integer that specifies the version of this format of the box.
> flags is a map of flags

This indicates the `flags` field for an `infe` box takes the value `0`. It's not entirely clear to me from the syntax description language (SDL) defined in MPEG‐4 (ISO/IEC 14496-1:2010) § 8, whether this is a requirement or a suggestion.

**Comment by rbouqueau** [comment]
The most recent value is more relaxed but that cw could make some additional checks on box extensions in general.

**Comment by cconcolato** [comment]
@baumanj can you clarify which test file would be wrong?

**Comment by baumanj** [comment]
All of the files in https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles/Microsoft

**Comment by cconcolato** [comment]
I just checked https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Microsoft/Chimera_10bit_cropped_to_1920x1008.avif?raw=true and it does have flags = 0. At least, according to https://gpac.github.io/mp4box.js/test/filereader.html

**Comment by baumanj** [comment]
I see `flags = 0` for the first `infe` box, but not for the second
![Screen Shot 2021-04-13 at 1 09 39 PM](https://user-images.githubusercontent.com/5906042/114614616-9c1b7680-9c59-11eb-80ed-d53623d9213f.png)

**Comment by wantehchang** [comment]
The current version of ISO BMFF (Reference number ISO/IEC 14496-12:2020(E)) allows the combination of `version >= 2` and `flags=1`. I believe this is what Romain Bouqueau referred to in his comment.

I quote from the end of Section 8.11.6.1 on page 88:

> The `flags` field of `ItemInfoEntry` with `version` greater than or equal to 2 is specified as follows:
> — (`flags` & 1) equal to 1 indicates that the item is not intended to be a part of the presentation.
> — (`flags` & 1) equal to 0 indicates that the item is intended to be a part of the presentation.

**Comment by cconcolato** [comment]
@dwsinger It seems that there was a regression in the ISOBMFF specification. 
[N17277 (output from the Macao meeting)](https://dms.mpeg.expert/doc_end_user/documents/120_Macau/wg11/w17277.zip) indicates:
```
aligned(8) class ItemInfoEntry
		extends FullBox('infe', version, flags) {
```
and also contains the text quoted by @wantehchang 
but the latest version [N19301 (output from Alpbach)](https://dms.mpeg.expert/doc_end_user/documents/130_Alpbach/wg11/w19301.zip) wrongly says:
```
aligned(8) class ItemInfoEntry
		extends FullBox('infe', version, 0) {
```

@baumanj in summary, I think the spec has a bug. Microsoft's files (at least the one I checked) seem correct, they set the flag only on the 'Exif' item which could match the interpretation that the 'Exif' item is not part of the presentation. I don't know how it would be presented anyway even with the flag not set ...

**Comment by baumanj** [comment]
Ah, that's so helpful. Thanks @wantehchang for pointing that out. I was looking at the 2015 version of ISOBMFF (ISO/IEC 14496-12) and that text was added later. And thanks for the clarification on the spec issue @cconcolato; whether I was misunderstanding the SDL was going to be my text question.

With that additional knowledge, I'll go ahead and close this. Is there an issue to track that spec bug, @cconcolato ?

**Comment by cconcolato** [comment]
Filed an issue with ISOBMFF https://github.com/MPEGGroup/FileFormat/issues/27
