### ISSUE TITLE
A typo in "Metadata OBUs, if present, shall match the values given in other item properties, such as the PixelInformationProperty or ColourInformationBox."

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/av1-avif#156]
Section 2.2.1. AV1 Item Configuration Property says:

> The syntax and semantics of the _**AV1 Item Configuration Property**_ are identical to those of the AV1CodecConfigurationBox defined in [AV1-ISOBMFF], with the following constraints:
> - ...
> - Metadata OBUs, if present, shall match the values given in other item properties, such as the PixelInformationProperty or ColourInformationBox.

I have a question about the last list item. None of the AV1 Metadata OBUs contains information equivalent to the PixelInformationProperty or the `nclx` type of ColourInformationBox. So the last list item apparently contains a typo. But I don't know how to correct it.

**Comment by wantehchang** [comment]
Since this list item is in v1.0.0 and is not new, we don't need to fix this in the new version of the spec.

**Comment by cconcolato** [comment]
Thanks for the report. You're correct. I think it was intended to say something along the lines of: information in OBUs (Sequence Header, Metadata) shall match information in properties, if a property exists that carries the same type of information.
