### ISSUE TITLE
In Section 2.2.2. Image Spatial Extents Property, FrameWidth should be changed to UpscaledWidth

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/av1-avif#157]
Section 2.2.2. Image Spatial Extents Property says:

> The semantics of the ispe property as defined in [HEIF] apply. More specifically, for AV1 images, it corresponds to the FrameWidth and FrameHeight values as defined in [AV1] for a frame that depends on the presence of the lsel and OperatingPointSelectorProperty properties as follows:

The word "FrameWidth" is incorrect. It should be changed to "UpscaledWidth". Similarly, the word "framewidth" in the Section "Terms defined by reference" should be changed to "upscaledwidth".

**NOTE:** I understand this is confusing and it is reasonable to think I could be wrong. For a proof, please review Section 7.18. Output process in the AV1 spec and look at how the variables `w` and `h` (the width and height of the output frame) are defined in 7.18.2. Intermediate output preparation process:

> The output of this process are the variables `w`, `h`, `subX`, and `subY` describing the format of the data in arrays `OutY`, `OutU`,
> and `OutV`.
> 
> If `show_existing_frame` is equal to 1, then the decoder should copy `OutY`, `OutU`, and `OutV` from a previously decoded
> frame as follows:
> - The variable `w` is set equal to `RefUpscaledWidth[ frame_to_show_map_idx ]`.
> - The variable `h` is set equal to `RefFrameHeight[ frame_to_show_map_idx ]`.
> - ...
>
> Otherwise (`show_existing_frame` is equal to 0), then the decoder should copy the current frame as follows:
> - The variable `w` is set equal to `UpscaledWidth`.
> - The variable `h` is set equal to `FrameHeight`.
> - ...

**Comment by leo-barnes** [comment]
Given the pasted snippet from the AV1 spec, this does look like a correct fix. Do we want to discuss it in a meeting, or are we confident enough that we can simply change it?
