### ISSUE TITLE
Suggestion: Remove "Update a1op to simple box" and "Update a1lx property syntax and semantics" from "Changes since v1.0.0 release"

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/av1-avif#158]
Section 9. Changes since v1.0.0 release contains the following two list items:

- Update a1op to simple box.
- Update a1lx property syntax and semantics.

I suggest we remove these two list items because they describe updates to changes made after v1.0.0 (i.e., the list item "Define properties for layered images.") rather than updates to v1.0.0.

There are two other list items that could be clarified slightly:

- Clarify that constraints on reduced flags apply to non-layered images.
- Remove wrong recommendations regarding still flags in image sequences.

I suggest changing "reduced flags" to "still flags" in the first list item for consistency. Then, it would be good to change "still flags" to "still picture flags" for clarify.

**Comment by cconcolato** [comment]
The idea was to have one entry per merged pull request as it was easy to track, but maybe that was not the best choice, maybe we sometimes need N links per change log entry, when multiple merged pull requests address the same change compared to v1.0.0.
