### ISSUE TITLE
Is there a typo in "The AV1 level for High Profile shall be 5.1 or lower."?

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/av1-avif#159]
Section 6.4. AVIF Advanced Profile says:

> The following additional constraints apply to all AV1 Image Items:
> 
> - The AV1 profile shall be the High Profile and the level shall be 6.0 or lower.

and:

> The following additional constraints apply only to AV1 Image Sequences:
> 
> - The AV1 profile shall be either Main Profile or High Profile.
> - The AV1 level for Main Profile shall be 5.1 or lower.
> - The AV1 level for High Profile shall be 5.1 or lower.

I am wondering if the last list item should read:

> - The AV1 level for High Profile shall be 6.0 or lower.

Otherwise, it seems to contradict the first list item:
> - The AV1 profile shall be the High Profile and the level shall be 6.0 or lower.

**Comment by leo-barnes** [comment]
No, I don't think it's a contradiction (image items are separate from image sequences which are coded pretty much like regular video tracks).
I think it's similar in most HEIF/MIAF profiles that image items allow a higher level than for image sequences. I can't remember the background for it, but it was probably some kind of HW limitation.

**Comment by wantehchang** [comment]
Leo: Thank you for your reply. I am surprised that the maximum level for the High Profile is different between image items and image sequences. I found the MIAF profiles that you referred to in MIAF Annex A.
