### ISSUE TITLE
4:4:4 chroma sub-sampling and profile "High"

### ISSUE THREAD

**Issue by lambdapioneer** [AOMediaCodec/av1-avif#16]
**Motivation**

Allowing 4:4:4 Chroma sub-sampling is critical to many application areas (e.g. graphical images or photographic content with overlays). AVIF should allow for storing image information with 4:4:4 chroma sub-sampling.

Comparison with other formats:
 - JPEG: supports 444 (e.g. mozjpeg uses 444 by default for higher quality values)
 - WebP: not supported unless lossless (see https://en.wikipedia.org/wiki/WebP#Restrictions)
 - HEVC: supported with `Main 4:4:4 Intra` profile (see https://en.wikipedia.org/wiki/High_Efficiency_Video_Coding#Version_2_profiles)

**Proposed change**

Change required reader profile to "High" or higher to allow 4:4:4 bit streams.

From the AV1 spec https://aomediacodec.github.io/av1-spec/av1-spec.pdf, p635:

> The Main profile supports YUV 4:2:0 or monochrome bitstreams with bit depth equal to 8 or 10. The Highprofile further adds support for 4:4:4 bitstreams with the same bit depth constraints. Finally, the Professional profile extends support over the High profile to also bitstreams with bit depth equal to 12, and also adds support for the 4:2:2 video format

**Other**

I'd suspect that 444 would play particularly well to the strength of the "chroma from luma prediction" in AV1: https://people.xiph.org/~xiphmont/demo/av1/demo1.shtml

See related issue: #15

**Comment by cconcolato** [comment]
I agree with the general idea. The group needs to have a discussion regarding the number of profiles/brands we want to have and their perimeter.

**Comment by mzso** [comment]
Why not have it as default? The codec would/could do better at throwing away color information than plain dumb 4:2:0/4:2:2 subsampling.

**Comment by lambdapioneer** [comment]
> Why not have it as default? The codec would/could do better at throwing away color information than plain dumb 4:2:0/4:2:2 subsampling.

Setting a default would be part of an encoder implementation. The specification simply says what's allowed :) And I feel that we don't want to exclude 4:2:0 to allow efficient extraction of frames from AV1 video.

If we have some documentation that shows that 4:4:4 out-performs 4:2:0 on AV1, we could add a note or a recommendation.
