### ISSUE TITLE
Need to require consistency between the a1op and the lsel properties

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/av1-avif#161]
The spec does not seem to require consistency between the `a1op` and `lsel` properties if both properties are associated with an AV1 Image Item. Section 2.3.2.2. Layer Selector Property says:

> The corresponding spatial layer shall be present in the bitstream and shall produce an output frame.

I think we should require that the spatial layer shall be present in the selected operating point (if `a1op` is present) or the operating point 0 (if `a1op` is absent).

**Comment by leo-barnes** [comment]
I would have thought `shall produce an output frame` implied that the layer is present in the selected operating point, but you're right that it's probably better to explicitly spell it out.

**Comment by wantehchang** [comment]
Leo: Thank you for the reply. Since the current wording is clear to you (or rather you can fill in the blank), we can close this issue.
