### ISSUE TITLE
Potential contradiction about the default operating point

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/av1-avif#162]
The spec seems to have a contradiction what the default operating point should be if no OperatingPointSelectorProperty is associated with an image item.

On the one hand, Section 2.2.2. Image Spatial Extents Property says:

> - In the absence of a `lsel` property associated with the item:
>   - If no OperatingPointSelectorProperty is associated with the item, the `ispe` shall document the dimensions of the last frame decoded when processing the operating point whose index is 0.

This seems to imply the default operating point is 0.

On the other hand, Section 2.3.1. Overview says:

> In the absence of an OperatingPointSelectorProperty associated with an AV1 Image Item, the AVIF renderer is free to process any Operating Point present in the AV1 Image Item Data.

This seems to imply there is no default operating point. So there seems to be a contradiction.

One can argue that there is no contradiction between these two sections as long as the AVIF renderer ignores the `ispe` property when `a1op` is absent and the AVIF renderer processes an operating point whose index is not 0. If this is the intention, please close this issue.

**Comment by leo-barnes** [comment]
I don't think there's really a contradiction here. Section 2.2.2 tells us which frame that the `ispe` documents. If the renderer chooses a different operating point than the one that the `ispe` points to, that is up to the renderer.

Otherwise we would need the `ispe` to document _all_ possible operating points if `a1op` is used.

**Comment by wantehchang** [comment]
Leo: Thank you for your response. Your last sentence seems to be missing a "not". Did you mean the following?

> Otherwise we would need the `ispe` to document _all_ possible operating points if `a1op` is **not** used.

**Comment by leo-barnes** [comment]
@wantehchang 
> Leo: Thank you for your response. Your last sentence seems to be missing a "not". Did you mean the following?
> 
> > Otherwise we would need the `ispe` to document _all_ possible operating points if `a1op` is **not** used.

Yup. Should have read it one more time before posting. 🙂
