### ISSUE TITLE
animals_00_multilayer_lsel.avif: both decoded frames have the same spatial_id

### ISSUE THREAD

**Issue by 0xC0000054** [AOMediaCodec/av1-avif#163]
The two layers have different width and height values,  but the same temporal_id and spatial_id.

Layer 0:

![aviflayer0](https://user-images.githubusercontent.com/26996983/123538588-f2457500-d6f2-11eb-8af7-245f1ab81620.PNG)

Layer 1:

![aviflayer1](https://user-images.githubusercontent.com/26996983/123538597-fffafa80-d6f2-11eb-86c9-247b05d3496b.PNG)

**Comment by leo-barnes** [comment]
How are you getting the spatial_id of the layers? If you're using libaom, there's a bug that @wantehchang fixed pretty recently that causes the wrong spatial_id to be returned. This is the issue: https://bugs.chromium.org/p/aomedia/issues/detail?id=2993

**Comment by 0xC0000054** [comment]
> How are you getting the spatial_id of the layers?

That is what is displayed in the debugger when using libaom 3.1.1.

> ...there's a bug that @wantehchang fixed pretty recently that causes the wrong spatial_id to be returned. This is the issue: bugs.chromium.org/p/aomedia/issues/detail?id=2993

I saw that after I opened this issue, that fix was committed after the release of libaom 3.1.1.

**Comment by leo-barnes** [comment]
@0xC0000054 
Can you try if the issue still reproduces with the fix from @wantehchang? The files should be correct as far as I can tell.

**Comment by 0xC0000054** [comment]
>  Can you try if the issue still reproduces with the fix from @wantehchang? The files should be correct as far as I can tell.

That patch did fix the issue, so the file is read correctly in libaom 3.1.2 and later.
