### ISSUE TITLE
AVIF should have a table of boxes and box versions

### ISSUE THREAD

**Issue by leo-barnes** [AOMediaCodec/av1-avif#167]
Cyril has created a prototype table of required boxes/box-versions for stills and image sequences which would be a good addition to the spec. This issue will track getting that added at some point.

**Comment by cconcolato** [comment]
#170 tries to address that

**Comment by wantehchang** [comment]
Leo: I just wanted to confirm with you that in AVIF v1.2.0 we do not need to add a Section 9.2 on "Image sequence boxes".

**Comment by leo-barnes** [comment]
> Leo: I just wanted to confirm with you that in AVIF v1.2.0 we do not need to add a Section 9.2 on "Image sequence boxes".

I think the whole thing with having a list of boxes is a "nice to have". It helps implementers by collecting information from ISOBMFF, HEIF, MIAF and AVIF into a single table with crucial information. But it doesn't really add any new requirements or restrictions, and the spec doc would work without it.

I think Cyril tried to make a corresponding table for sequences, but ended up getting stuck since there are so many boxes needed that the table got too large. We can try to create such a table for v1.3.0, but I don't think we need it for v1.2.0.
