### ISSUE TITLE
AVIF omits to select shared constraints from MIAF

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-avif#169]
MIAF defines constraints (Section 8) that can be shared by profiles, but they have to be explicitly selected. Among them is 'self-containment', which is assumed in AVIF but not explicitly stated. The others are: "single-layer", "grid-limit", "single-track", "edit-lists", "matched-duration". AVIF should clarify which ones are applicable.

**Comment by y-guyon** [comment]
Thank you for the detailed presentation.

I agree with the proposition.

I would make it a "shall" only when it simplifies the implementation.  
For example does `single-track` allows the reader to stop at the first encountered track, or would it mean that the reader has to parse the whole file to make sure there is only one track? For the former I do not see the change of behavior so why not making it a "shall", but for the latter this is actually extra work and I would avoid it.

Regarding the added spec complexity, there is not much to consider as this is just toggling some already existing profiles basically.

**Comment by leo-barnes** [comment]
> I would make it a "shall" only when it simplifies the implementation. For example does `single-track` allows the reader to stop at the first encountered track, or would it mean that the reader has to parse the whole file to make sure there is only one track? For the former I do not see the change of behavior so why not making it a "shall", but for the latter this is actually extra work and I would avoid it.

I think it would basically allow the reader to stop at the first encountered _supported_ track (given that we can have alternates). It was meant to simplify implementation in that parsers will not have to deal with how to surface multiple image sequences.

**Comment by leo-barnes** [comment]
> But what keeps the reader from doing the same without that constraint? There is no constraint that forces the reader to surface _all_ image sequences, right?

True. But the point with MIAF is really to lay down a number of hard and soft recommendations on how to **create** files that will be as portable as possible. 

It's ambiguous what a file with multiple sequences means so it's not really portable, hence why MIAF added the restriction saying the file does not contain multiple sequences.

Anyone who adheres to the shared MIAF constraints will have been forced to create a file that is at least somewhat portable and following best practices.

**Comment by wantehchang** [comment]
@vigneshvg Vignesh: Could you review Leo's suggestions in https://github.com/AOMediaCodec/av1-avif/issues/169#issuecomment-2345667395? Some of those constraints are in your areas of expertise. Thanks!
