### ISSUE TITLE
Invalid test files: transforms before `ImageSpatialExtentsProperty` (`ispe`)

### ISSUE THREAD

**Issue by baumanj** [AOMediaCodec/av1-avif#178]
Per HEIF (ISO/IEC 23008-12:2017) § 6.5.3.1:
> Every image item shall be associated with one property of this type, prior to the association of all transformative properties.

The following test files violate this property:
- [kimono.crop.avif](https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Link-U/kimono.avif)
- [kimono.mirror-horizontal.avif](https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Link-U/kimono.mirror-horizontal.avif)
- [kimono.mirror-vertical.avif](https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Link-U/kimono.mirror-vertical.avif)
- [kimono.mirror-vertical.rotate270.avif](https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Link-U/kimono.mirror-vertical.rotate270.avif)
- [kimono.mirror-vertical.rotate270.crop.avif](https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Link-U/kimono.mirror-vertical.rotate270.crop.avif)
- [kimono.rotate90.avif](https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Link-U/kimono.rotate90.avif)
- [kimono.rotate270.avif](https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Link-U/kimono.rotate270.avif)

**Comment by rbouqueau** [comment]
Seems impelemnted, cf:
>  [heif][Rule #11] Error: Item ID=1: transformative property "clap" (index=2) found prior to "ispe"

Can we close?

**Comment by baumanj** [comment]
This issue isn't about reporting the error, it's about the fact that there are invalid test files in the repo
