### ISSUE TITLE
Update multi-layer content to conform to new 'lsel' wording

### ISSUE THREAD

**Issue by leo-barnes** [AOMediaCodec/av1-avif#181]
Once #180 lands, we need to update the test content to conform to the new wording.

**Comment by leo-barnes** [comment]
Re-opening this to track updating the Xiph content.

@tdaede:
Do you have some time to update the Xiph multilayer content to the latest wording in the spec? If not, I can try doing it manually, but if you have some easy way to do it that will most likely be faster.

**Comment by tdaede** [comment]
@leo-barnes ah indeed I still have the scripts to do this. I need to double check that the current GPAC implementation is correct bu tthen I can rerun them and PR some new images.

**Comment by wantehchang** [comment]
@tdaede Please also update the `a1lx` boxes in your test images to the definition in v1.1.0. The problem is that the `layer_size` array should contain the sizes of the layers themselves, not the cumulative sizes.

**Comment by tdaede** [comment]
Oh whoops, I thought this was about the layer_size array.

For lsel, could you clarify on what needs updating? Do you want additional files that contain a 0xFFFF lsel? AFAIK the ones that exist are still valid according to the new wording?

**Comment by wantehchang** [comment]
Thomas: We don't need additional files. We need to make sure all the existing layered images contain an `lsel` box. If a layered image doesn't have an 'lsel' box, please add a 0xFFFF `lsel`.

This is to conform to HEIF, which says an `lsel` box is mandatory for layered images.

**Comment by leo-barnes** [comment]
This has been done.
