### ISSUE TITLE
Item property definition tables

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/av1-avif#182]
Minor thing, but should all the definition tables for item properties contain `(per item)` in the **Mandatory** and **Quantity** rows? 
Looks like this is common practice in HEIF but it is mixed in AVIF (see `av1C`)

**Comment by cconcolato** [comment]
I'm ok to harmonize with HEIF. I understand what `(per item)` means for *Quantity* but what does it mean for *Mandatory*? How can a property be mandatory for anything else than an item?
