### ISSUE TITLE
Spec should define file extensions and MIME types

### ISSUE THREAD

**Issue by aklemets** [AOMediaCodec/av1-avif#20]
The spec should define file extensions and MIME types. It currently does not.

**Comment by aklemets** [comment]
HEIF actually uses 5-letter file extensions for files that include image sequences. I think there may be some confusion caused by the info on the Nokia web site. That info is non-normative. I checked how the official registration of the MIME type of image/heic-sequence on IANA, and the file extension is .heics (i.e., a 5-letter extension.)
Here is the IANA link: [https://www.iana.org/assignments/media-types/image/heic-sequence](https://www.iana.org/assignments/media-types/image/heic-sequence)

**Comment by lambdapioneer** [comment]
Thanks for the info :) In that case `avifs` plays along very well with the HEIF extension `heifs`
