### ISSUE TITLE
different bit depth and resolution of avif images test on Pixel4 XL(Android 13)

### ISSUE THREAD

**Issue by Vlitop** [AOMediaCodec/av1-avif#213]
I pushed some 8bit YUV420 avif images and 10bit YUV420 avif images in Pixel4 XL(Android 13)respectively, only the former one can present normally. I really want to figure out why this happend?

Additionally, I tested that 8bit YUV420 avif image on the Pixel in different resolution(64*64, 128*128, 256*256, 512*512, 1024*1024, 1920*1080, 2560*1440), all of them can normally displayed on my screen except 2560 *1440. Dose anyone know the reason?

**Comment by leo-barnes** [comment]
This is an issue tracker for the AVIF specification. It really has very little to do with specific implementations. You will receive much more informative answers by opening issues in bug trackers for the respective device and OS.

Assuming the files are valid (you can try running them through https://gpac.github.io/ComplianceWarden-wasm/avif.html), one possible explanation may be codec limitations on the specific device.
