### ISSUE TITLE
Shared coded data between image and sequence contradicts still_picture=1

### ISSUE THREAD

**Issue by y-guyon** [AOMediaCodec/av1-avif#216]
Running [libavif's ChangeSettingTest.AOM](https://github.com/AOMediaCodec/libavif/blob/12e066686892df1c8201cfb0d8d6c68ad248c872/tests/gtest/avifchangesettingtest.cc#L104-L110) with `-DAVIF_ENABLE_COMPLIANCE_WARDEN=ON` gives:

> Specification description: AVIF v1.0.0, 19 February 2019
> https://aomediacodec.github.io/av1-avif/
> [avif][Rule #3] Warning: [ItemId=1] still_picture flag set to 0
> [avif][Rule #4] Warning: [ItemId=1] reduced_still_picture_header flag set to 0

This matches [AV1-AVIF v1.1.0](https://aomediacodec.github.io/av1-avif/v1.1.0.html#image-item) (also v1.0.0):

> If the AV1 Image Item Data consists of a single frame (i.e. when using a single layer),
> - It should have its `still_picture` flag set to 1.
> - It should have its `reduced_still_picture_header` flag set to 1.

libavif currently generates a `meta` box and image items alongside tracks when encoding sequences. I think this is the expected behavior because of ISO 23008-12 (HEIF):
> Files containing an image sequence should also contain a file-level MetaBox with a primary item that is an image item as specified in Clause 6, for cases in which temporal presentation is either undesirable, or not possible (e.g. printing).  
> NOTE The primary item can share coded data with one of the intra-coded images in the sequence.

However the "shared coded data" will not have its `still_picture` and `reduced_still_picture_header` fields set to 0 because it is a sequence. So the note contradicts the other recommendations.

The recommendations on `still_picture` and `reduced_still_picture_header` were removed for Image Sequences in https://github.com/AOMediaCodec/av1-avif/pull/112. I suggest we do the same for Image Items.

**Comment by leo-barnes** [comment]
@y-guyon 
Do we want to try to fix this for v1.2.0?

**Comment by y-guyon** [comment]
I sent https://github.com/AOMediaCodec/av1-avif/pull/228 if we want to simplify the specification but I do not think the real issue is in AV1-AVIF.

Although `(i.e. when using a single layer)` is misleading in my opinion, `still_picture=1` for a **single frame** makes sense. I would say it is more of an issue on the ComplianceWarden side, which may not have access to the number of frames in order to properly emit that warning. So removing the constraint in AV1-AVIF is the easiest approach, but updating ComplianceWarden is necessary in all cases.

What do you think?

**Comment by vigneshvg** [comment]
Relevant discussion from a compliance warden PR: https://github.com/gpac/ComplianceWarden/pull/41 that disabled this specific check.

But i think i just interpreted "single layer" to mean "single frame". I agree that replacing the term with "single frame" makes more sense.

**Comment by wantehchang** [comment]
If we want to keep the recommendation, we can change it from

```
If the AV1 Image Item Data consists of a single frame (i.e. when using a single layer),
```

to

```
If the AV1 Image Item Data is in an AV1 coded video sequence that contains only one coded frame,
```
