### ISSUE TITLE
testFiles/Netflix/avis/alpha_video.avif has incorrect `auxl` box

### ISSUE THREAD

**Issue by vigneshvg** [AOMediaCodec/av1-avif#217]
The item reference entry inside the `auxl` box must contain `item_id` of the item to which is it auxiliary to (which is 4). The current value is 0 which is incorrect (and in fact disallowed by the spec since item_id can never be 0.

To correct the file, byte number 259 (0-index) must be updated to 0x04 instead of 0x00.

**Comment by leo-barnes** [comment]
This was fixed by #201
