### ISSUE TITLE
Multilayer text is confusing

### ISSUE THREAD

**Issue by leo-barnes** [AOMediaCodec/av1-avif#220]
We have this snippet in the spec (note bold text):
> In the absence of an [OperatingPointSelectorProperty](https://github.com/AOMediaCodec/av1-avif/issues/new#operatingpointselectorproperty) associated with an [AV1 Image Item](https://github.com/AOMediaCodec/av1-avif/issues/new#av1-image-item), the AVIF renderer is free to process any [Operating Point](https://aomediacodec.github.io/av1-spec/av1-spec.pdf) present in the [AV1 Image Item Data](https://github.com/AOMediaCodec/av1-avif/issues/new#av1-image-item-data). **In particular, when the [AV1 Image Item](https://github.com/AOMediaCodec/av1-avif/issues/new#av1-image-item) is composed of a unique [Operating Point](https://aomediacodec.github.io/av1-spec/av1-spec.pdf), the [OperatingPointSelectorProperty](https://github.com/AOMediaCodec/av1-avif/issues/new#operatingpointselectorproperty) should not be present**. If an [OperatingPointSelectorProperty](https://github.com/AOMediaCodec/av1-avif/issues/new#operatingpointselectorproperty) is associated with an [AV1 Image Item](https://github.com/AOMediaCodec/av1-avif/issues/new#av1-image-item), the op_index field indicates which [Operating Point](https://aomediacodec.github.io/av1-spec/av1-spec.pdf) is expected to be processed for this item.

I assume the text is trying to say that if the AV1 payload only consists of a single operating point, the a1op property should not be present, but I find the current text a bit confusing. How about something like this?

```diff
-In particular, when the AV1 Image Item is composed of a unique Operating Point, the OperatingPointSelectorProperty should not be present
+In particular, when the AV1 Image Item Data is composed of a single Operating Point, the OperatingPointSelectorProperty should not be present
```

**Comment by leo-barnes** [comment]
@cconcolato @y-guyon @podborski 
Thoughts?

**Comment by cconcolato** [comment]
Both are equivalent to me. The first one was referring to the logical structure (Image item), the proposed text is referring to the physical structure (image item data).

**Comment by leo-barnes** [comment]
After thinking on it some more I think the existing text is actually more correct. Closing.
