### ISSUE TITLE
Add tag for v1.1.0

### ISSUE THREAD

**Issue by leo-barnes** [AOMediaCodec/av1-avif#221]
We don't have any tag for the v1.1.0 release

**Comment by leo-barnes** [comment]
@cconcolato 
How do we get the v1.1.0 release to show up as a tagged release? Do we simply add a tag for it?

**Comment by cconcolato** [comment]
I don't remember exactly but I think so.

**Comment by leo-barnes** [comment]
I tagged 77bd20d59d7cade4ab98f276ff4828433ebd089b as that is the same as the published spec but also allows for compiling without errors.
