### ISSUE TITLE
avif with pixi version 1

### ISSUE THREAD

**Issue by bradh** [AOMediaCodec/av1-avif#247]
This was originally going to be a comment on https://github.com/strukturag/libheif/issues/1306 but probably makes more sense here.

I think what libheif now has for box parsing is a good approach for interoperability, but I wonder if its actually compliant.

https://aomediacodec.github.io/av1-avif/#avif-required-boxes says `pixi` version 0 is required, and:

> The "Version(s)" column in the following table lists the version(s) of the boxes allowed by this brand. Other versions of the boxes shall not be used.

So a file that claims to be AVIF but has `pixi` version 1 isn't actually AVIF. In practice, this means it would not be compliant to write files with `avif` as a `major_band` or `compatible_brand` when using `pixi` version 1.

I had high hopes for using the `channel_label` for geospatial imagery, but now I'm less confident.

Options:
 - change the allowed pixi version to "0, 1", which would be a forward incompatible change for av1-avif - existing consumers may reject newer files, even though all the required information is actually available.
 - add a different property to describe the "bottom half" of the proposed `pixi` version 1 data

**Comment by leo-barnes** [comment]
This is a good point. The list of boxes and required versions is a new thing that has not yet been published, so we can definitely change it.

I have actually been thinking about this a bit myself:
> The "Version(s)" column in the following table lists the version(s) of the boxes allowed by this brand. Other versions of the boxes shall not be used.

Potentially we may want to call out that it's ok to use versions other than these only for optional boxes. After all, it's perfectly ok to ignore non-essential item properties if you don't understand.

Specifically with regards to `pixi` v1, I think the latest thinking is that we don't actually need to bump the version as long as we only append to the box and don't make any changes to the parsing or meaning of existing fields.

**Comment by bradh** [comment]
> Specifically with regards to `pixi` v1, I think the latest thinking is that we don't actually need to bump the version as long as we only append to the box and don't make any changes to the parsing or meaning of existing fields.

-0.

Parsers should be able to check that they got all the data. If I'm reading a `pixi` box with version = 0, and there is junk at the end of the box that isn't meant to be there, a strict parser should reasonably reject the file, and a less strict parser should at least log a warning.

**Comment by leo-barnes** [comment]
@bradh 
> Parsers should be able to check that they got all the data. If I'm reading a pixi box with version = 0, and there is junk at the end of the box that isn't meant to be there, a strict parser should reasonably reject the file, and a less strict parser should at least log a warning.

That interpretation is not actually compliant with ISOBMFF. Section 4.2.2 says this:
> Future editions of this document may add syntax at the end of a box derived from FullBox and keep on using an already specified version value, if it is not essential to parse such added syntax. When a parser has not reached the end of a box derived from FullBox as defined by the values of the size or largesize field (as appropriate) but does not recognize the remaining syntax elements, it shall ignore and skip the remaining of the box.

**Comment by bradh** [comment]
> That interpretation is not actually compliant with ISOBMFF. Section 4.2.2 says this:
> 
> > Future editions of this document may add syntax at the end of a box derived from FullBox and keep on using an already specified version value, if it is not essential to parse such added syntax. When a parser has not reached the end of a box derived from FullBox as defined by the values of the size or largesize field (as appropriate) but does not recognize the remaining syntax elements, it shall ignore and skip the remaining of the box.

I'm not seeing that in ISO/IEC 14496-12:2022 Section 4.2.2 "Object definitions". Is that from a newer (draft?) version?

> With that said, I think we should still set a flag when adding extra data so that there is some kind of indication on what it is.

If its different, it should be a different version. Its a weak objection though, and kind of off-=topic for AVIF.

**Comment by leo-barnes** [comment]
> > That interpretation is not actually compliant with ISOBMFF. Section 4.2.2 says this:
> > > Future editions of this document may add syntax at the end of a box derived from FullBox and keep on using an already specified version value, if it is not essential to parse such added syntax. When a parser has not reached the end of a box derived from FullBox as defined by the values of the size or largesize field (as appropriate) but does not recognize the remaining syntax elements, it shall ignore and skip the remaining of the box.
> 
> I'm not seeing that in ISO/IEC 14496-12:2022 Section 4.2.2 "Object definitions". Is that from a newer (draft?) version?

It's in the 8th edition DIS. Which I'm kind of surprised has not been published yet given how long it's been worked on.

> > With that said, I think we should still set a flag when adding extra data so that there is some kind of indication on what it is.
> 
> If its different, it should be a different version. Its a weak objection though, and kind of off-=topic for AVIF.

I have to disagree on that one. It makes adding optional metadata to existing boxes very painful to roll out. I have to say I think the ISOBMFF wording it the right way of thinking about it. If neither parsing nor meaning of existing fields have changed, you don't need to bump the version to add more stuff.

**Comment by wantehchang** [comment]
Brad: A good way to add new syntax elements to a box derived from FullBox without changing the version is to use a formerly reserved bit in `flags` to indicate the presence of the new syntax elements.

Leo: When adding new syntax elements we must set a flag, otherwise a parser of the new syntax will consider data produced by old encoders as incomplete.

So for a given `version` and `flags`, it is possible to detect whether there is extraneous data at the end of a box derived from FullBox. So a parser should be able to reject extraneous data for the values of `flags` it knows about. For example, a parser that only knows about `version = 0` and `flags = 0` of the 'pixi' box should be able to reject data after the for loop in the following definition if `version` and `flags` are both equal to 0:

```
aligned(8) class PixelInformationProperty
extends ItemFullProperty('pixi', version = 0, flags = 0) {
   unsigned int(8) num_channels;
   for (i=0; i<num_channels; i++) {
      unsigned int(8) bits_per_channel;
   }
}
```
