### ISSUE TITLE
Image properties in the table in Section 9.1.2 should be at Level 3

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/av1-avif#268]
Leo,

The image properties in the table in Section 9.1.2 are documented to be at Level 1. Since their containing box is `ipco` and `ipco` is at Level 2, I think all the image properties should be at Level 3.

**Comment by wantehchang** [comment]
Leo: Perhaps the levels in the table in Section 9.1.2 are unrelated to the levels in the table in Section 9.1.1?

I guess the levels in the table in Section 9.1.1 are the levels in the file, whereas the levels in the table in Section 9.1.1 are the levels in the containing box (`meta` or `ipco`)?

**Comment by leo-barnes** [comment]
> I guess the levels in the table in Section 9.1.1 are the levels in the file, whereas the levels in the table in Section 9.1.1 are the levels in the containing box (meta or ipco)?

Yes, I think that is what @cconcolato was going for. I think the current structure works, but is slightly confusing. Alternatives that I can think of:
1. Change the table to look like the one in 9.1.1. We could then remove the "Containing box" column.
2. Remove the levels from the columns and always state the containing box in the "Containing box" column.

Thoughts?

**Comment by leo-barnes** [comment]
> 2. Remove the levels from the columns and always state the containing box in the "Containing box" column.

The drawback of this approach is that it's not as easy to visually see the tree structure.

**Comment by y-guyon** [comment]
> 1. Change the table to look like the one in 9.1.1. We could then remove the "Containing box" column.

I would like that. I added a comment pushing for that somewhere.
