### ISSUE TITLE
Clarify the requirements on the second input image item in the Sample Transform Derived Image Item examples

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/av1-avif#283]
In the two Sample Transform Derived Image Item examples, the second input image item is described to have "the same dimensions and number of samples as the first input image item". The "[same] number of samples" part of this requirement is not strict enough. It should be replaced by "same number of channels and the same chroma subsampling (or lack thereof)", from [Section 4.2.3.1](https://aomediacodec.github.io/av1-avif/#sample-transform-definition).

**Comment by leo-barnes** [comment]
Agreed. This probably needs slightly stricter language. @y-guyon, do you have time to think on it? If not I can try to take a look later this week.
