### ISSUE TITLE
Provide reference library and CLI tools (libavif) 

### ISSUE THREAD

**Issue by EwoutH** [AOMediaCodec/av1-avif#44]
For easy integration and experimentation a reference library and command line tools for AVIF should be provided somewhere. It could have a similar structure to [webp](https://developers.google.com/speed/webp/), which provides a libary `libwebp` and command line tools `cwebp` and `dwebp`.

I would suggest the following 6 packages to be created:

**.avif (single frame)**

- `libavif`: Encoding and decoding .avif library
- `cavif`: Command line .avif encoding tool
- `davif`: Command line .avif decoding tool

**.avifs (multi frame / animation)**

- `libavifs`: Encoding and decoding .avifs library
- `cavifs`: Command line .avifs encoding tool
- `davifs`: Command line .avifs decoding tool

In this configuration, the avif tools could be very lightweight, since only the AV1 intra encoding and decoding tools are needed. the avifs tools extend avif with the inter en- and decoding code. `cavifs` could replace both [gif2webp](https://developers.google.com/speed/webp/docs/gif2webp) and [img2webp](https://developers.google.com/speed/webp/docs/img2webp).

**Comment by EwoutH** [comment]
Someone already gave it a try: https://github.com/joedrago/avif

**Comment by EwoutH** [comment]
@cconcolato @aklemets Congratulations on officially releasing version 1.0.0 of the spec!

Are there any plans for an official reference library (as far as you are aware of)?

**Comment by cconcolato** [comment]
Thanks. As of now, there is no plan to have an "official" reference library for the AVIF layer on top of libaom. We rely on non-official OSS like libavif or mp4box. If you think anything is missing, AOM could certainly consider developing/sponsoring the missing bricks.

**Comment by EwoutH** [comment]
@cconcolato Thanks for the quick response! I think CLI applications are essential for quick feedback loops with users (testing, debugging, profiling, etc.). [cwebp](https://developers.google.com/speed/webp/docs/cwebp) and [dwebp](https://developers.google.com/speed/webp/docs/dwebp) where great in that regard.

**Comment by ledyba-z** [comment]
@EwoutH 

Hi! We are [Link-U](https://github.com/link-u]), a Japanese digital comics publishing company.

We are strongly interested to use AVIF in production.

We are developing encoder/decoder commands ourself, so please introduce them:

## [cavif](https://github.com/link-u/cavif) - avif encoder, using libaom directly.

https://github.com/link-u/cavif

Despite libavif supports libaom and rav1e, cavif supports just libaom as a backend. Instead, it allows usesr to control most all of encoding options in libaom, to tune image quality ultimately. Please see long-long-long [SYNPOSIS](https://github.com/link-u/cavif#synopsis).

## [davif](https://github.com/link-u/davif) - avif decoder, using dav1d directly.

https://github.com/link-u/davif

We made it to check the result of cavif. It supports rotation/mirror/crop feature, libavif does not support yet.

## [libavif-container](https://github.com/link-u/libavif-container)

https://github.com/link-u/libavif-container

AVIF file manipulating library. cavif and davif use this.

**Comment by ledyba-z** [comment]
If you are interested, how about host them in   
https://github.com/AOMediaCodec/cavif,  
https://github.com/AOMediaCodec/davif, and
https://github.com/AOMediaCodec/libavif-container ?

**Comment by cconcolato** [comment]
The group discussed this issue in its meeting today. https://github.com/AOMediaCodec/libavif/ is the reference implementation for AVIF. Other implementations are very welcome and can be listed in the https://github.com/AOMediaCodec/av1-avif/wiki. I'm closing this issue.

**Comment by dmak** [comment]
If somebody could update on the issue: Git repositories started by Link-U are outdated, and [cloned repository](https://github.com/avif-community/cavif/tags) was released in March 2020, so seems to be unmaintained as well.

Any hint on where to get a good reference CLI that uses the library (except [ffmpeg](https://nixsanctuary.com/ffmpeg-now-supports-jpeg-xl-and-avif-how-to-convert-images/))?
