### ISSUE TITLE
Create conformance file with odd framesizes

### ISSUE THREAD

**Issue by lambdapioneer** [AOMediaCodec/av1-avif#45]
There is value in having conformance files that have odd frame sizes. Currently, all test image files have a frame size that is divisible by 8.

By default, AV1/libaom will internally use a frame size `aomImage->w, aomImage->h` that is a multiple of 8(?). However, it also exposes the to-be-displayed framesize `aomImage->d_w, aomImage->d_h`and the to-be-rendered framesize  `aomImage->r_w, aomImage->r_h`. (I don't know if there's an important difference between `d_w` and `r_w`)

Adding the conformance files makes sure that the right dimensions are referenced for the output. I suggest the following resolutions:

 - Single image: 63x65, 4:2:0
 - Single image: 65x63, 4:4:4

Maybe we want to also include a derived grid image with the "sub images" having odd resolutions?

**Comment by ledyba-z** [comment]
@lambdapioneer @cconcolato 
Hi, I created the test images with odd framesizes.
(I also created 4:2:2 test images)

Please use it!

https://github.com/link-u/avif-sample-images#fox-parade---odd-dimensions-images

**Comment by cconcolato** [comment]
This issue is closed with #67
