### ISSUE TITLE
File extension is misleading

### ISSUE THREAD

**Issue by vrubleg** [AOMediaCodec/av1-avif#51]
`.avif` file extension is very misleading. It looks very similar to `.avi`, and a user may expect that it should be a video, but it is not. Why `.webp` extension is not utilized? If `.webp` can't be used because the internal container has been changed (from RIFF to ISOBMFF), we could utilize `.webi` (Web Image) or `.aomi` (AOMedia Image), for example.

**Comment by lambdapioneer** [comment]
I think the current file extension is adequate. Personally, I don't see the risk of confusing it with `.avi` video files. Many interfaces hide file extensions by default and also they'd be significantly different in file size in most cases.

At the moment `.avif` is already [widely used and referenced already](https://www.google.com/search?q=avif).

Also, implementations are free to use [`.heif` and `.avif` interchangeably](https://aomediacodec.github.io/av1-avif/#avif-mime-definition). I'd find the risk of confusion with another image format `.webp`/`.webi` more concerning given the change of the underlying constraints to MiAF.

I suggest to stay with `.avif` and close this issue :)

**Comment by cconcolato** [comment]
Closing per proposed recommendation above.
