### ISSUE TITLE
Add avif.js to the wiki

### ISSUE THREAD

**Issue by Kagami** [AOMediaCodec/av1-avif#58]
Hi.

I would like to add link for [AVIF polyfill](https://github.com/Kagami/avif.js) to the wiki. Seems like it's locked for non-collaborators so could you please put it on [Implementations page](https://github.com/AOMediaCodec/av1-avif/wiki)?

Thank you.

**Comment by cconcolato** [comment]
Very nice! Thank you for the report. 

Can we get an idea of what features of AVIF it supports: image items, image sequences, both? alpha? What are the profiles/levels supported (I guess what the underlying decoder supports)? 

Do you have suggested text to be added to the wiki page?

**Comment by Kagami** [comment]
>image items, image sequences, both?

Currenly no, it returns BMP image data instead of AVIF and BMP doesn't support multiple image items.
Though decoding to APNG or WebP might work.

>alpha?

Currently decodes to BGR24 to minimize memory consumption, but BMP supports alpha channel so quite easy to implement. I'm not sure whether browsers support transparent AV1 though.

>What are the profiles/levels supported (I guess what the underlying decoder supports)?

Yes, same as in browser for AV1 video (though not everything currently works, I'm not fixing all metadata fields of moov/av1C yet).

>Do you have suggested text to be added to the wiki page?

Maybe something like
```
[avif.js](https://github.com/Kagami/avif.js) polyfill adds support for displaying AVIF in a browser.
Requires workable AV1 in `<video>` tag.
```

**Comment by cconcolato** [comment]
Thanks for the text. I don't have a problem with adding your tool. I'll give other people some time to object if they want to and maybe I'll mention that in the next Still Picture WG call, and then I'll add it.

 AVIF Images with an alpha channel are actually done by providing 2 AV1 images: one for the RGB part and one, encoded as monochrome, to provide the alpha channel. I don't if AV1 decoders in browsers support decoding of monochrome images. If they do, a step to merge the RBG and A images would still be needed to produce your BMP.

**Comment by Kagami** [comment]
Would you mind adding [go-avif](https://github.com/Kagami/go-avif) while we are at it too? It's Go library and small CLI utility for encoding AVIF files. (I used gpac as a reference so I hope I didn't make major mistakes in ISOBMFF structure.)

**Comment by cconcolato** [comment]
Done for both.

**Comment by Kagami** [comment]
Thanks!
