### ISSUE TITLE
AVIF should have a different extension/mime-type for lossless mode, as well as additional restrictions

### ISSUE THREAD

**Issue by mzso** [AOMediaCodec/av1-avif#60]
Since the format allows lossless encoding, it should have these to distinguish it from lossy images.
In this case of course the container should only allow such image parameters that are in line of the image being lossless for the file to be valid. (Not sure what else could be done to guarantee that the image is lossless beside a checksum/hashcode)
Otherwise the image should be rejected.

Lossless images of course have some distinct use cases. And it helps if the user can tell whether he acquired a lossless image, or saved a lossless image just by choosing the lossless AVIF variant. One expects them to be editable and re-encodable without quality loss.

**Comment by cconcolato** [comment]
The AOM Still Picture WG discussed this issue during its call today. The group is not sure that there will be lossless-only implementations, that would justify defining a new MIME type and decided to close this issue. If people have more information to support this use case, they can always reopen this issue or open a new one if they have a different approach than MIME type.

**Comment by mzso** [comment]
Well, at least it was discussed...
