### ISSUE TITLE
Add Nightly VLC to players in wiki

### ISSUE THREAD

**Issue by baumanj** [AOMediaCodec/av1-avif#69]
https://github.com/AOMediaCodec/av1-avif/wiki#demuxers--players makes no mention of [nightly VLC](https://nightlies.videolan.org/), but it is able to display (albeit with some issues) both AVIF and AVIS files.

I'd have just submitted a PR, but for changes to a wiki, GitHub doesn't seem to have a simple workflow.

**Comment by cconcolato** [comment]
Done. Thank you.
