### ISSUE TITLE
Add expected rendering examples for test files

### ISSUE THREAD

**Issue by baumanj** [AOMediaCodec/av1-avif#70]
I'm working on AVIF support for Firefox, and the sample images in https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles have been very helpful, but given the dearth of renderers in the current ecosystem, it's difficult to have confidence in the correctness of output.

For example, I'm pretty confident that [Netflix/avif/cosmos_frame01000_yuv420_8bpc_bt709_g22_qlossless.avif](https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Netflix/avif/cosmos_frame01000_yuv420_8bpc_bt709_g22_qlossless.avif) is rendering correctly based on this screenshot of my prototype rendering in browser:
![cosmos_frame01000_yuv420_8bpc_bt709_g22_qlossless](https://user-images.githubusercontent.com/5906042/76132409-b64f4380-5fc7-11ea-947a-6926f51bcc74.png)

But I assumed the same frame in 10-bit [(cosmos_frame01000_yuv420_10bpc_bt2020_hlg_qlossless.avif)](https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Netflix/avif/cosmos_frame01000_yuv420_10bpc_bt2020_hlg_qlossless.avif) should look essentially the same, causing me to doubt my output when it did not:
![cosmos_frame01000_yuv420_10bpc_bt2020_hlg_qlossless](https://user-images.githubusercontent.com/5906042/76132457-04644700-5fc8-11ea-8e8a-066923935fde.png)

However, the 10-bit version rendered by VLC nightly looks quite similar:
![cosmos_frame01000_yuv420_10bpc_bt2020_hlg_qlossless](https://user-images.githubusercontent.com/5906042/76132511-337ab880-5fc8-11ea-98a6-fd91522d478a.png)

As does the version rendered by Windows:
![cosmos_frame01000_yuv420_10bpc_bt2020_hlg_qlossless](https://user-images.githubusercontent.com/5906042/76132521-3fff1100-5fc8-11ea-964a-9806f96db9a8.png)

Though I have my doubts about relying on the correctness of other renderers based on the Windows output for [cosmos_frame01000_yuv444_8bpc_bt709_g22_qlossless.avif](https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Netflix/avif/cosmos_frame01000_yuv444_8bpc_bt709_g22_qlossless.avif):
![cosmos_frame01000_yuv444_8bpc_bt709_g22_qlossless](https://user-images.githubusercontent.com/5906042/76132664-ef3be800-5fc8-11ea-94fc-35bb5bf235ff.png)

For comparison here's that same input as rendered by Firefox:
![cosmos_frame01000_yuv444_8bpc_bt709_g22_qlossless](https://user-images.githubusercontent.com/5906042/76132814-b3ede900-5fc9-11ea-9ffc-612c09528c5c.png)

And VLC:
![cosmos_frame01000_yuv444_8bpc_bt709_g22_qlossless](https://user-images.githubusercontent.com/5906042/76132805-aafd1780-5fc9-11ea-8d25-89410f45e213.png)

If it would be possible to see what the input was, it would be a great help in validating the correctness of the output.

**Comment by cconcolato** [comment]
Thanks for reaching out. It's great to see AVIF support progressing in Firefox. 
Regarding the difference 8b/10b, please note that the color volumes are not the same BT.709/Gamma 2.2 vs BT.2020 HLG in the examples you gave. 
Regarding the 444 rendering, it does seem that Windows rendering is not correct. @aklemets may be able to help ?

> If it would be possible to see what the input was, it would be a great help in validating the correctness of the output.

What decoder are you using? I doubt the decoded values are wrong. Most likely, the rendering differ because of how the values are interpreted. What kind of data would you need to validate the "correctness of the output" on the screen?

**Comment by baumanj** [comment]
> What decoder are you using? I doubt the decoded values are wrong. Most likely, the rendering differ because of how the values are interpreted. What kind of data would you need to validate the "correctness of the output" on the screen?

Currently libaom, but working on switching to dav1d.

I suppose it's a tricky thing to say what "correct" should be when there are a lot of other factors that play into the way things eventually look on screen, but I think the most useful thing would be having access to the raw input (in whatever format) that was used to created the encoded images.

Also, pardon my ignorance on some of the finer technical points. I'm new to the codec/video space and am still learning.

**Comment by joedrago** [comment]
Hello! Exciting stuff, seeing AVIF make its way to Firefox. I think I can see the issue hiding in this sentence:

> But I assumed the same frame in 10-bit (cosmos_frame01000_yuv420_10bpc_bt2020_hlg_qlossless.avif) should look essentially the same, causing me to doubt my output when it did not:

Those two images were derived from the same HDR source frame (from Cosmos Laundromat), but they are encoded with different color profiles. 

The first is in the BT709 color gamut with a 2.2 gamma transfer function, which is 99% identical to sRGB, so it will look good without paying attention at all to the color profile (if your render pipeline doesn't think in color profiles and assumes sRGB). 

The second one that you cited, however, is encoded in the BT.2020 color gamut, with the HLG curve for its transfer function. Sprinkled throughout that directory are other combinations as well (BT.2020 + PQ, etc). Without interpreting/converting these pixel values with the appropriate color profile, they're definitely going to display incorrectly.

I am not familar with Firefox's capabilities with regards to handling color profiles, HDR rendering, etc. Are there any pre-existing, generic color pipelines in Firefox when decoding an image which let you feed it an ICC profile or some other means to indicate its color profile?

**Comment by joedrago** [comment]
(I forgot to introduce myself and just barged, sorry! I'm the author of libavif, and I generated those images.)

**Comment by baumanj** [comment]
Hey @joedrago, thanks for the explanation! I just started at Mozilla in November, so I am also just learning about Firefox's graphics pipeline and I'll need to get back to you about how we handle color profiles, but this at least gives some more context about what I'm seeing.

Back to the original issue, do you think there's any value in including the HDR source frames in the repo for the benefit of folks developing renderers?

**Comment by joedrago** [comment]
I guess I'm not understanding the request. If I were to decode these AVIFs but maintain the pixel values and color profiles in them, and save them in some pre-existing format (PNG, etc), you'd hit the same issue. The problem here is that (for example) is not that you're not interpreting (255,0,0) as red, but that you're interpreting it as the _wrong_ red.

The original HDR frames were encoded in 12bpc, P3 color gamut, on the PQ curve. They're available online (Blender Cloud or something?), but without honoring that color profile, you're going to run into the same issue. The acquisition of the correct YUV or RGB pixel values isn't what is messing up your render here, is the interpretation of them.

(If this all sounds like nonsense, you can ping me on video-dev or gchat for a crash course.)

**Comment by joedrago** [comment]
If, tangentially, you just want to make sure you're interpreting 10bpc and 12bpc correctly and don't want to bother with color profiles just yet, I'd be happy to convert the original (bt709+g2.2) image you are happy with into 10bpc and 12bpc for you, so you can at least check those boxes off.

**Comment by joedrago** [comment]
[10bpc-and-12bpc-avifs.zip](https://github.com/AOMediaCodec/av1-avif/files/4301275/10bpc-and-12bpc-avifs.zip)

**Comment by joedrago** [comment]
Those are encodes-of-encodes, so there might be a visually imperceptible codepoint drift, but those 4 images in that zip should look the same as the one you are already happy with.

(they are also not HDR, just like the original)

**Comment by jaikrishnan** [comment]
Based on the discussion from yesterday's meeting, let's leave this open as more established rendering paths become available for canonical comparison between AVIF and other established image formats. 
I believe there was also a suggestion with 16 bit png, if @baumanj has a related proposal feel free to add it here. I'll also move this to non-blocking

**Comment by baumanj** [comment]
Here's an example from Link-U of the sort of reference which might be useful: https://resources.link-u.co.jp/avif/images.html

**Comment by cconcolato** [comment]
We will create an HTML page with example rendering for non-HDR images, and for HDR images we will add SDR rendering and expected differences.

**Comment by baumanj** [comment]
Any chance we could get similar treatment for the non-Netflix test files? Correct alpha support, especially with premultiplication variations can be somewhat tricky.
