### ISSUE TITLE
Add cavif/davif to the wiki

### ISSUE THREAD

**Issue by ledyba-z** [AOMediaCodec/av1-avif#71]
Hi.

I would like to add link for [cavif](https://github.com/link-u/cavif) and [davif](https://github.com/link-u/davif) to the wiki.
They are used to generate [test images I prepared](https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles/Link-U) and decode them again to compare to the original images.

While libavif supports many encoders and decoders, cavif and davif just uses libaom to encode and dav1d to decode. Instead, cavif and davif let you control each encoder and decoder in detail.

Thank you.

**Comment by ledyba-z** [comment]
It may be helpful if there is a link to [new sample images](https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles/Link-U) in [here](https://github.com/AOMediaCodec/av1-avif/wiki#example-files).

**Comment by cconcolato** [comment]
Done.

**Comment by ledyba-z** [comment]
Thanks!
