### ISSUE TITLE
How about add additional constraints: (bit depth of primary image == bit depth of alpha image)

### ISSUE THREAD

**Issue by ledyba-z** [AOMediaCodec/av1-avif#74]
According to https://github.com/AOMediaCodec/av1-avif/issues/68, it is valid AVIF file whose bit-depth of primary image and that of alpha plane are different.

(For example, AVIF file with 8bpc primary image and 10bpc alpha plane).

However, as @joedrago says

> I think this creates a lot of pain points, corner cases, and complexity for very little gain, if I'm being honest.
> https://github.com/AOMediaCodec/libavif/issues/86

I really agree with him. In fact, I support those image in [cavif](https://github.com/link-u/cavif) and [davif](https://github.com/link-u/davif), but it made the code a little bit complex and make very difficult to write test (because there are many combinations to test...).

How about add additional constraints, such as "The bit-depth of the primary image and that of alpha image should be the same".

**Comment by paperboyo** [comment]
From a purely design POV, I could imagine it being beneficial to have eg. a 1-bit image and an 8-bit alpha. That’s what PNG (at least through pngquant) already kind-of supports.

**Comment by ledyba-z** [comment]
@paperboyo 
Unfortunatelly, 1-bit image is not supported. 8, 10 and 12 bits are supported.
(And it looks difficult to add 1-bit image support to AV1, if I understand correctly)

**Comment by ledyba-z** [comment]
I think we can discuss also about these additional constraints:

 - Primary image and alpha image should have the same size (width, height), relates to #75 
 - Alpha image should always be full-ranged, related to 
   - https://github.com/AOMediaCodec/libavif/issues/86,
    - https://github.com/AOMediaCodec/libavif/issues/91

**Comment by paperboyo** [comment]
My bad, I’m definitely not familiar enough with all possible features of AVIF. And, to the [point made](https://github.com/AOMediaCodec/libavif/issues/86#issuecomment-594397583) in the linked thread, there are plenty of formats with every possible obscure feature, but zero adoption. 99% of AVIFs will be simple, flat, no-alpha, 8-bit JPEG replacements, IMHO, and that’s great: I can’t wait!

That said, I can still see a _potential_ usefulness of alpha having different bit-depth (opposite example would be an 8-bit alpha with a higher bit-depth HDR image, for better compression ratio). Alpha being different dimensions, less so, but stretching imagination: smaller than image to only encode what’s necessary and bigger than image if eg. some software would allow animating alpha and image planes independently.

**Comment by aklemets** [comment]
The rules for Alpha images are defined the way they are to allow for the most compression efficiency. In a typical case, you really only need one bit for alpha (0=transparent, 1=not transparent).

Let's say the main image is a 10-bit color image. It would be very inefficient to require a second color image to encode the 1-bit alpha information. So, the spec recommends that alpha images should be encoded as monochrome images, and a 8-bit monochrome image should compress more efficiently than a 10-bit one.

Also, there are cases where it might not be important to encode the alpha information at the same resolution as the main image. Let's say you have a high-resolution image of a person sitting in front of a web cam, and alpha is used to remove the background. It might be completely fine if the alpha is +/- 1 or 2 pixels off in that case. (Probably, the software that detects the edge between the person and the background is not that accurate anyway.) In a scenario like this, it would make sense to encode the alpha image at a lower resolution as well.

**Comment by jaikrishnan** [comment]
From discussion in the AOM group, there is general agreement that this is an acceptable change since:

- In the vast majority of cases the alpha bit depth with match the color planes
- Tooling like libavif and browser implementations don't support a bit depth mismatch (although this isn't a full blocker as these implementations could change)
- Edge cases like [aklements mentioned](https://github.com/AOMediaCodec/av1-avif/issues/74#issuecomment-605667088) are rare enough that implementers could handle the additional required bits. 

**Please comment on this issue in the next two weeks with any use cases which would require _not_ making this change**
