### ISSUE TITLE
Wiki Page Related Question: How to create a keyframe file?

### ISSUE THREAD

**Issue by GrandArth** [AOMediaCodec/av1-avif#87]
>MP4Box from the GPAC Project can create HEIF files and in particular AVIF files with Image Items from the Key Frames of an AV1 video stream, with the following command-line: MP4Box -add-image file.av1:time=0 -brand avif file.avif.

```
ffmpeg -i 1.jpg -c libaom-av1 -strict -2 -crf 20 1.mkv  -y
```
I used this line to encode a jpg image into av1 stream.
```
MP4Box -add-image 1.mkv:time=0 -brand avif file.avif
```
Then i tried this to get a avif file, but failed.
output:
```
[Importer] Unknown input file type for "1.mkv"

        Error: Corrupted Data in file/stream
```
I noticed that in the wiki it writes file.av1 but i failed to find any tools for av1 file generating.
Any ideas?
Is it possible to generate av1 key frame files with ffmpeg or i have to use other tools to batch convert files into avif?

**Comment by cconcolato** [comment]
MP4Box calls *.av1 plain streams of OBU. The file could be equally named *.obu. I don't know how to produce that with ffmpeg. Alternatively, MP4Box should support IVF files that ffmpeg should be able to produce. (cc @rbouqueau)

**Comment by GrandArth** [comment]
Tried IVF files, the whole process seems flawless yet the resulted AVIF file is somehow unable to decode (on latest Win10, avif encoded with Colortist/Caivf can be decoded and display properly.).
example files here:
[example.zip](https://github.com/AOMediaCodec/av1-avif/files/4869691/example.zip)

**Comment by cconcolato** [comment]
It renders fine in [Vantage](https://github.com/joedrago/vantage) and Chrome Canary. Not sure what's wrong with it. @aklemets ?

**Comment by GrandArth** [comment]
Vantage works fine.
[example.zip](https://github.com/AOMediaCodec/av1-avif/files/4869844/example.zip)
I packed a avif (encoded with goavif) that can be decoded with Micorsoft Paint.
Could it be a colorspace issue?
It remind me of HEIC images (HEVC), heic with yuv444 can not be decode with Plugin in Micorsoft Store, yuv420 works fine.
Since ImageMagick can't identify avif files directly, i would re-encode some image and find out if that is the issue.

**Comment by GrandArth** [comment]
I encoded some VIF file with the following code seprately:
```
ffmpeg -i "1.jpeg" -c libaom-av1 -strict -2  -crf 20 -vf "crop=trunc(iw/2)*2:trunc(ih/2)*2" -pix_fmt yuv420p -sws_flags spline+accurate_rnd+full_chroma_int -color_range 1 -colorspace 5 -color_primaries 5 -color_trc 6   1.ivf
```
```
ffmpeg -i "1.jpeg" -c libaom-av1 -strict -2  -crf 20 -vf "crop=trunc(iw/2)*2:trunc(ih/2)*2" -pix_fmt yuv444p -sws_flags spline+accurate_rnd+full_chroma_int -color_range 1 -colorspace 5 -color_primaries 5 -color_trc 6   1.ivf
```
None of them can be decoded by win10 decoder (in micorsoft paint) and Firefox, yet they are both available in Vantage.

**Comment by aklemets** [comment]
@GrandArth the "1.avif" file that is included in example.zip is missing the Primary Item Box. The Primary Item Box ('pitm') is mandatory in MIAF (and thus also AVIF). That is why the file is being rejected in Windows 10.

**Comment by GrandArth** [comment]
Thx for the intel, this issues can be considered closed now.
