### ISSUE TITLE
Decide whether we want to add metadata for YCoCg-R (or lossless in general) now, or wait until AV2 / not at all

### ISSUE THREAD

**Issue by dwbuiten** [AOMediaCodec/av1-avif#89]
Given that losslessly encoding GBR data using the reversible YCoCg-R transform yields ~7-15% (as per the mailing list; I can reproduce that data here if necessary), is it worth considering whether we want to spend time extending one of the specs, or adding some metadata that indicate that:

- That the encoded data is in YCoCg-R format. (There is no CICP entry for YCoCg-R, only YCoCg)
- That, for example, a 10-bit bitstream that contains YCoCg-R can guarantee that once the inverse YCoCg-R transform is applied, that the output will fit in 8-bits (since converting 8-bit RGB with YCoCg-R yields 8-bit luma and 9-bit chroma, and has to be encoded as a 10-bit AV1 stream).

The other options are:

- Deciding we don't care about lossless - this is a legitimate choice, since a purpose-designed codec for lossless like WebP-LL, JPEG-XR / FUIF, etc. can usually outperform a hybrid block based codec like AV1.
- Deciding we want to wait until AV2 to care - i.e. too much work to justify right now for any benefits it would provide.

**Comment by joedrago** [comment]
Just to clarify for myself, such a mechanism would be something like:

* Take 8bpc or 10bpc RGB data during AVIF encoding and convert to 10bpc/12bpc YCoCg-R (12bpc RGB would be unsupported in this mode)

* Encode this new 10/12bpc YCoCg-R as CICP Identity(0) (or new CICP?)

* Add some sort of signaling (as an essential property or new CICP?) that the AV1 data is n+2 bits and YCoCg-R, and should have its depth rescaled to n-2 bpc

I will note that switching from 8bpc to 10bpc has decoding perf/memory costs, if we decide to attempt this.

**Comment by dwbuiten** [comment]
Unrelated to any decision we make, it may be worth engaging with ITU to update H.273 with YCoCg-R?

**Comment by cconcolato** [comment]
This discussion led to the proposal of adding a code point to CICP.
