### ISSUE TITLE
Should use different brand major for Collection or Sequences

### ISSUE THREAD

**Issue by fcartegnie** [AOMediaCodec/av1-avif#9]
Just like other codec mappings:
heic/heix vs hevc/hevx
avci vs avcs

**Comment by aklemets** [comment]
The other file formats have different file extensions for files that include image sequences. It sounds like you are asking for different brand identifiers. But that's not what the other file formats use the brand identifiers for. For example 'heic' and 'heix' is used to distinguish between SDR and HDR, not between sequence and non-sequence files.

**Comment by lambdapioneer** [comment]
According to http://nokiatech.github.io/heif/technical.html (table I), for HEIF files heic/heix indicate an image and hevc/heix indicate a sequence when used in a HEIF file. Being SDR/HDR respectively.

**Comment by aklemets** [comment]
You are right that for HEVC there is a separate brand for image sequences. I had missed that earlier. But I would caution against using the Nokia web site as a reference at the info on that site might be stale. 
I agree with you then that we should add a separate brand for AV1 image sequence files.

**Comment by cconcolato** [comment]
Discussed during 9/26 AOMI meeting. Agreement to define different brands for images vs sequences.
