### ISSUE TITLE
Include version numbers in normative references to other standards

### ISSUE THREAD

**Issue by negge** [AOMediaCodec/av1-avif#90]
The Normative References section of the AVIF specification (https://aomediacodec.github.io/av1-avif/#normative) includes a link to the unversioned AV1 spec (https://aomediacodec.github.io/av1-spec/av1-spec.pdf) in [AV1], see:

https://github.com/AOMediaCodec/av1-avif/blob/master/index.html#L1495

Before release an updated version of the AVIF spec, we should version links to any external specification documents, including that for AV1 (e.g., https://github.com/AOMediaCodec/av1-spec/releases/tag/v1.0.0-errata1).  This is particularly important as there is an update to the AV1 spec currently under consideration to address the missing "center" chroma siting issue (#88).

**Comment by cconcolato** [comment]
We revised our thoughts and think the normative references that we have are expected to change in a backwards-compatible way.
