### ISSUE TITLE
Make av1C box optional

### ISSUE THREAD

**Issue by kornelski** [AOMediaCodec/av1-avif#95]
AFAIK all this data is a redundant copy of data from the AV1 payload. Firefox is able to decode images without the `av1C` box present. 

The need to add `av1C` box requires adding `iprp`, `ipco`, and `ipma` boxes. That's a relatively large amount of metadata.

**Comment by cconcolato** [comment]
Thanks again for the feedback. 

I agree that there is an overhead to creating the `av1C` box and the associated boxes. There are several reasons why the `av1C` box was mandatory:
- for compatibility with the [AV1-ISOBMFF](https://aomediacodec.github.io/av1-isobmff/) video format which requires it. This allows you to round-trip from the video format to the image format to the video format without losing information and without requiring the tool regenerate and `av1C` box on the fly
- it allows tools to determine the characteristics of the bitstream without having to dig in the `mdat` box. For example, you can determine the profile and level of each item 'easily' without having to download the `mdat`. 

Note that if you have multiple images with the same codec configuration (typical when a camera captures images or bursts), the `av1C` can be shared.

**Comment by kornelski** [comment]
For conversion from BMFF, could `av1C` requirement be limited to avif-sequence files, and not item-based files? I'm not even sure if I understand the use-case for single-image files, since image items are supposed to be keyframes, so you can't roundtrip an arbitrary video files.

There are `compatible_brands` for specifying profiles. Could it be worked around by defining that if `av1C` is absent, then the image has to conform to some pre-defined set of features?

I have Web usage in mind, where `av1C` is just useless overhead. The main use case is single-item (+ alpha) AVIF with as little metadata as possible. Camera burts or fancy features are not that interesting in the web context. Actual browser support will dictate a de-facto web-compatible profile.

**Comment by cconcolato** [comment]
The group discussed this issue. We fully recognize that the data is redundant, but we think it is beneficial to know width/height/depth ... from the box without having to parse or decode the bitstream. We decide to keep the `av1C` mandatory.
