### ISSUE TITLE
Support for premultiplied alpha?

### ISSUE THREAD

**Issue by kornelski** [AOMediaCodec/av1-avif#96]
Does AVIF support premultiplied alpha color space? If not, would it be possible to add it?

I'm talking about encoding color channels instead of uncorrelated YUV as Y×a, U×a, V×a, and then having the decoder undo the conversion with Y÷a, U÷a, V÷a. Such color space is used by JPEG-XT.

This way transparent areas of the image are naturally replaced with black, and colors in semi-transparent areas of the image have lower amplitude, which typically makes them get compressed appropriately more.

Currently decorrelated alpha makes efficient compression of images with alpha challenging, because it needlessly preserves color of fully transparent pixels, and requires encoders to use heuristics for filling in transparent areas with cheap-to-encode colors (e.g to avoid wasting bits on edges between opaque pixels and meaningless color of transparent pixels).

**Comment by cconcolato** [comment]
From MIAF section 7.3.5.2:
> An item reference (respectively track reference) of type 'prem' from the master image item (respectively
master image sequence track) to the auxiliary image item (respectively auxiliary image sequence track)
signals that the master image(s) is (are) pre-multiplied by the alpha value. If the item or track reference is
not present, the master image(s) is (are) not pre-multiplied by the alpha value. For further detail on the
interpretation of alpha planes, see subclause 6.7.
