### ISSUE TITLE
Broken links for pixi reference

### ISSUE THREAD

**Issue by kornelski** [AOMediaCodec/av1-avif#97]
The links for boxes:

> colr, pixi or pasp,

Link to ISO homepage, not any spec.

**Comment by cconcolato** [comment]
Thanks. We'll try to fix it. In the meantime, note that the [Terms defined by reference](https://aomediacodec.github.io/av1-avif/#index-defined-elsewhere) section indicates in which spec they are defined.

**Comment by kornelski** [comment]
Could you quote more of the other specs? ISO expects me to buy the HEIF spec, and get it *on paper*. From reverse-engineering other implementations it seems `pixi` just just image width/height. It's not worth 178 swiss francs to learn that :)

**Comment by cconcolato** [comment]
The HEIF spec is available for free.
Don't ask me why ISO presents it this way, but they add the following at the top of the pages of freely available specs:
> The electronic version of this International Standard can be downloaded from the ISO/IEC Information Technology Task Force (ITTF) web site

If you follow the "downloaded" link, you'll get the spec:
https://standards.iso.org/ittf/PubliclyAvailableStandards/c066067_ISO_IEC_23008-12_2017.zip

**Comment by kornelski** [comment]
Wow, that's great. Thank you for the tip.

**Comment by wantehchang** [comment]
Kornel: Among the ISO standards that the AVIF spec refers to, the only one that is not publicly available is MIAF.
